// <auto-generated />
using System;
using MatrixPortfolio.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MatrixPortfolio.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MatrixPortfolio.Api.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MatrixPortfolio.Api.Models.ProfileEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProfileEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "name",
                            Value = "Henrique Dionisio Ferreira"
                        },
                        new
                        {
                            Id = 2,
                            Key = "headline",
                            Value = "Middle-level C# Developer // waking up from the Matrix"
                        },
                        new
                        {
                            Id = 3,
                            Key = "about",
                            Value = "I build APIs and web apps with C#, .NET and Angular. This portfolio itself is a fullstack project: ASP.NET Core + EF Core + PostgreSQL on the back, Angular on the front — deployed for free on Render + Neon + Netlify."
                        },
                        new
                        {
                            Id = 4,
                            Key = "email",
                            Value = "jessicas2mirelly1704@gmail.com"
                        },
                        new
                        {
                            Id = 5,
                            Key = "github",
                            Value = ""
                        },
                        new
                        {
                            Id = 6,
                            Key = "linkedin",
                            Value = ""
                        });
                });

            modelBuilder.Entity("MatrixPortfolio.Api.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("LiveUrl")
                        .HasColumnType("text");

                    b.Property<string>("RepoUrl")
                        .HasColumnType("text");

                    b.Property<string>("TagsCsv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Real-time monitoring dashboard built with ASP.NET Core + SignalR and Angular. Streams live metrics over WebSockets with a terminal-inspired UI.",
                            DisplayOrder = 1,
                            IsPublished = true,
                            LiveUrl = "",
                            RepoUrl = "https://github.com/your-user/nebuchadnezzar-dashboard",
                            TagsCsv = "C#,.NET 8,Angular,SignalR",
                            Title = "Nebuchadnezzar Dashboard"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "JWT authentication microservice with refresh-token rotation, rate limiting and PostgreSQL persistence. Deployed on Docker.",
                            DisplayOrder = 2,
                            IsPublished = true,
                            RepoUrl = "https://github.com/your-user/zion-auth",
                            TagsCsv = "C#,JWT,PostgreSQL,Docker",
                            Title = "Zion Auth Gateway"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Online code execution sandbox: Angular frontend queues jobs to a .NET worker that compiles/runs snippets in isolated processes.",
                            DisplayOrder = 3,
                            IsPublished = true,
                            RepoUrl = "https://github.com/your-user/construct-runner",
                            TagsCsv = ".NET,Angular,RabbitMQ",
                            Title = "Construct Code Runner"
                        });
                });

            modelBuilder.Entity("MatrixPortfolio.Api.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Backend",
                            DisplayOrder = 0,
                            Level = 85,
                            Name = "C# / .NET"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Backend",
                            DisplayOrder = 0,
                            Level = 80,
                            Name = "ASP.NET Core Web API"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Backend",
                            DisplayOrder = 0,
                            Level = 78,
                            Name = "Entity Framework Core"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Frontend",
                            DisplayOrder = 0,
                            Level = 72,
                            Name = "Angular"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Frontend",
                            DisplayOrder = 0,
                            Level = 70,
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Database",
                            DisplayOrder = 0,
                            Level = 65,
                            Name = "PostgreSQL"
                        },
                        new
                        {
                            Id = 7,
                            Category = "DevOps",
                            DisplayOrder = 0,
                            Level = 55,
                            Name = "Docker"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
